-- 과일로 만든 아이스크림 고르기
SELECT FLAVOR
FROM FIRST_HALF
WHERE FLAVOR IN (
    SELECT FLAVOR FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
)
AND TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC

-- ★ 12세 이하인 여자 환자 목록 출력하기
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO -- ★ IFNULL
FROM PATIENT
WHERE GEND_CD = 'W'
AND AGE <= 12
ORDER BY AGE DESC, PT_NO

-- 상위 n개 레코드
SELECT NAME FROM ANIMAL_INS
WHERE DATETIME IN (
    SELECT MIN(DATETIME) FROM ANIMAL_INS
)
-- 타 풀이 (★ LIMIT)
SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1