-- 5월 식품들의 총매출 조회하기
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (SUM(AMOUNT) * A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A, FOOD_ORDER B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND YEAR(B.PRODUCE_DATE) = 2022
AND MONTH (B.PRODUCE_DATE) = 5
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID

-- ★ 그룹별 조건에 맞는 식당 목록 출력하기
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE -- ★ DATE_FORMAT(format, '')
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
AND A.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT